-- CAPSTONE-1 Database Schema (v1.0)
-- Privacy-Preserving Security & Threat Telemetry Schema
-- STRICT MANDATE: No passwords, OTPs, CVVs, access tokens, or raw form values

CREATE TABLE IF NOT EXISTS service_profiles (
    service_id VARCHAR(64) PRIMARY KEY,
    service_name VARCHAR(128) NOT NULL,
    category VARCHAR(64) NOT NULL,
    declared_behavior TEXT,
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS service_domains (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    service_id VARCHAR(64) NOT NULL,
    domain VARCHAR(255) NOT NULL,
    is_primary BOOLEAN DEFAULT FALSE,
    FOREIGN KEY (service_id) REFERENCES service_profiles(service_id)
);

CREATE TABLE IF NOT EXISTS model_versions (
    model_id VARCHAR(64) PRIMARY KEY,
    version VARCHAR(32) NOT NULL,
    model_type VARCHAR(64) NOT NULL,
    sha256_hash VARCHAR(64) NOT NULL,
    is_active BOOLEAN DEFAULT TRUE,
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS policy_versions (
    policy_id VARCHAR(64) PRIMARY KEY,
    version VARCHAR(32) NOT NULL,
    description TEXT,
    is_active BOOLEAN DEFAULT TRUE,
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS observations (
    observation_id VARCHAR(64) PRIMARY KEY,
    collection_id VARCHAR(64) NOT NULL,
    device_id VARCHAR(128) NOT NULL DEFAULT 'device-unknown',
    device_platform VARCHAR(128) DEFAULT '',
    page_domain VARCHAR(255) NOT NULL,
    page_url_sanitized VARCHAR(1024) NOT NULL,
    is_https BOOLEAN NOT NULL,
    form_count INTEGER NOT NULL DEFAULT 0,
    input_count INTEGER NOT NULL DEFAULT 0,
    script_count INTEGER NOT NULL DEFAULT 0,
    requested_data_types TEXT,
    privacy_policy_url TEXT DEFAULT '',
    terms_url TEXT DEFAULT '',
    threat_level VARCHAR(32),
    model_score REAL,
    policy_action VARCHAR(32),
    observed_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_obs_domain ON observations(page_domain);
CREATE INDEX IF NOT EXISTS idx_obs_time ON observations(observed_at);
CREATE INDEX IF NOT EXISTS idx_srv_domain ON service_domains(domain);

-- Versioned, validated M1 metadata; no payload/body/header columns.
CREATE TABLE IF NOT EXISTS events_sanitized (
    session_id UUID NOT NULL,
    tab_id INTEGER NOT NULL,
    event_seq BIGINT NOT NULL CHECK (event_seq > 0),
    document_id TEXT,
    event_type TEXT NOT NULL,
    event JSONB NOT NULL,
    received_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (session_id, tab_id, event_seq)
);
CREATE INDEX IF NOT EXISTS idx_events_document ON events_sanitized(document_id);

-- Assessment revisions reference the event sequence used, retaining policy requests separately
-- from observed UI/submission receipts. Strict API models own this bounded JSON structure.
CREATE TABLE IF NOT EXISTS assessments_sanitized (
    session_id UUID NOT NULL,
    tab_id INTEGER NOT NULL,
    event_seq BIGINT NOT NULL,
    document_id TEXT,
    report JSONB NOT NULL,
    received_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (session_id, tab_id, event_seq)
);
