-- CAPSTONE-1 Database Schema (v1.0)
-- Privacy-Preserving Security & Threat Telemetry Schema
-- STRICT MANDATE: No passwords, OTPs, CVVs, access tokens, or raw form values

CREATE TABLE IF NOT EXISTS service_profiles (
    service_id VARCHAR(64) PRIMARY KEY,
    service_name VARCHAR(128) NOT NULL,
    category VARCHAR(64) NOT NULL,
    declared_behavior TEXT,
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS service_domains (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    service_id VARCHAR(64) NOT NULL,
    domain VARCHAR(255) NOT NULL,
    is_primary BOOLEAN DEFAULT FALSE,
    FOREIGN KEY (service_id) REFERENCES service_profiles(service_id)
);

CREATE TABLE IF NOT EXISTS model_versions (
    model_id VARCHAR(64) PRIMARY KEY,
    version VARCHAR(32) NOT NULL,
    model_type VARCHAR(64) NOT NULL,
    sha256_hash VARCHAR(64) NOT NULL,
    is_active BOOLEAN DEFAULT TRUE,
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS policy_versions (
    policy_id VARCHAR(64) PRIMARY KEY,
    version VARCHAR(32) NOT NULL,
    description TEXT,
    is_active BOOLEAN DEFAULT TRUE,
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS observations (
    observation_id VARCHAR(64) PRIMARY KEY,
    collection_id VARCHAR(64) NOT NULL,
    page_domain VARCHAR(255) NOT NULL,
    page_url_sanitized VARCHAR(1024) NOT NULL,
    is_https BOOLEAN NOT NULL,
    form_count INTEGER NOT NULL DEFAULT 0,
    input_count INTEGER NOT NULL DEFAULT 0,
    script_count INTEGER NOT NULL DEFAULT 0,
    requested_data_types TEXT,
    threat_level VARCHAR(32),
    model_score REAL,
    policy_action VARCHAR(32),
    observed_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_obs_domain ON observations(page_domain);
CREATE INDEX IF NOT EXISTS idx_obs_time ON observations(observed_at);
CREATE INDEX IF NOT EXISTS idx_srv_domain ON service_domains(domain);
